### ISSUE TITLE
Diseño de las medallas

### ISSUE THREAD

**Issue by juanAFernandez** [ButterFlyDevs/BrainStudio#3]
Hay que buscarse iconos de cinco medallas disintas. En concreto la página [thenounproject](https://thenounproject.com/search/?q=medal). Más ideas.

**Comment by juanAFernandez** [comment]
Las medallas para el Juego 1 están diseñadas y puestas en uso.

**Comment by JA-Gonz** [comment]
Idem medallas juego 2. Y he sacado mi lado julandrón con esos colorines en la medalla, pero me gusta :+1:

**Comment by juanAFernandez** [comment]
Las medallas del juego 3, 4 y 5  también están diseñadas y puestas en uso. Doy esta issue como concluida.

**Comment by JA-Gonz** [comment]
No tiene que ver con la medalla, pero dejo el enlace del icono "touch" que he cogido para las capturas de pantalla de Help:

http://www.flaticon.com/free-icon/hand-pointer_70655
